2012-05-31 20:35:56,306 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:35:56,306 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:41:53,545 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:41:53,545 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:46:01,556 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:46:01,556 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:46:45,277 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:46:45,277 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:47:18,580 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:47:18,580 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:49:28,996 ERROR EU-001:El usuario Carlos67 ya se encuentra registrado
2012-05-31 20:49:28,996 ERROR EU-001:El usuario Carlos67 ya se encuentra registrado
2012-05-31 20:49:28,996 ERROR EU-001:El usuario Carlos67 ya se encuentra registrado
2012-05-31 20:51:18,332 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:51:18,332 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:51:18,332 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:51:23,541 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:51:23,541 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:51:23,541 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:15,209 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:15,209 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:15,209 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:49,748 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:49,748 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:54:49,748 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:55:24,725 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:55:24,725 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:55:24,725 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:55:24,725 ERROR EU-001:El usuario Carlos15 ya se encuentra registrado
2012-05-31 20:56:16,503 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:56:16,503 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:56:16,503 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:56:16,503 ERROR EU-008:Error el usuario Carlos666 tiene un token vigente
2012-05-31 20:57:57,030 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:57:57,030 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:57:57,030 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:57:57,030 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:58:05,087 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:58:05,087 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:58:05,087 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 20:58:05,087 ERROR EU-005:Token no valido para el usuario Carlos80
2012-05-31 21:14:17,689 ERROR EU-004:El token del usuario Carlos80 ha expirado
2012-05-31 21:14:17,689 ERROR EU-004:El token del usuario Carlos80 ha expirado
2012-05-31 21:14:17,689 ERROR EU-004:El token del usuario Carlos80 ha expirado
2012-05-31 21:14:17,689 ERROR EU-004:El token del usuario Carlos80 ha expirado
2012-05-31 21:15:00,407 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:00,407 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:00,407 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:00,407 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:08,638 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:08,638 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:08,638 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:08,638 ERROR EU-010:Error el token enviado por el usuario Carlos80 para eliminar su cuenta es incorrecto
2012-05-31 21:15:35,650 ERROR EU-011:Error el token enviado por el usuario Carlos180 debe verificar su nickname y password
2012-05-31 21:15:35,650 ERROR EU-011:Error el token enviado por el usuario Carlos180 debe verificar su nickname y password
2012-05-31 21:15:35,650 ERROR EU-011:Error el token enviado por el usuario Carlos180 debe verificar su nickname y password
2012-05-31 21:15:35,650 ERROR EU-011:Error el token enviado por el usuario Carlos180 debe verificar su nickname y password
2012-05-31 21:18:28,639 ERROR EU-011:Error el token enviado por el usuario Carlos80 debe verificar su nickname y password
2012-05-31 21:18:28,639 ERROR EU-011:Error el token enviado por el usuario Carlos80 debe verificar su nickname y password
2012-05-31 21:18:28,639 ERROR EU-011:Error el token enviado por el usuario Carlos80 debe verificar su nickname y password
2012-05-31 21:18:28,639 ERROR EU-011:Error el token enviado por el usuario Carlos80 debe verificar su nickname y password
2012-05-31 21:19:08,853 ERROR EU-010:Error el token enviado por el usuario Carlos666 para eliminar su cuenta es incorrecto
2012-05-31 21:19:08,853 ERROR EU-010:Error el token enviado por el usuario Carlos666 para eliminar su cuenta es incorrecto
2012-05-31 21:19:08,853 ERROR EU-010:Error el token enviado por el usuario Carlos666 para eliminar su cuenta es incorrecto
2012-05-31 21:19:08,853 ERROR EU-010:Error el token enviado por el usuario Carlos666 para eliminar su cuenta es incorrecto
2012-05-31 21:21:01,457 ERROR EC-014:Error el usuario Ciscoi envio un token incorrecto
2012-05-31 21:21:01,457 ERROR EC-014:Error el usuario Ciscoi envio un token incorrecto
2012-05-31 21:21:01,457 ERROR EC-014:Error el usuario Ciscoi envio un token incorrecto
2012-05-31 21:21:01,457 ERROR EC-014:Error el usuario Ciscoi envio un token incorrecto
2012-05-31 21:21:28,698 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:21:28,698 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:21:28,698 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:21:28,698 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:26:57,051 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:26:57,051 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:26:57,051 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:26:57,051 ERROR EC-013:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:28:52,858 ERROR EC-014:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:28:52,858 ERROR EC-014:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:28:52,858 ERROR EC-014:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:28:52,858 ERROR EC-014:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:30:23,273 ERROR EC-018:Error la respuesta enviado por el usuario Armen no esta asociada al comentario
2012-05-31 21:30:23,273 ERROR EC-018:Error la respuesta enviado por el usuario Armen no esta asociada al comentario
2012-05-31 21:30:23,273 ERROR EC-018:Error la respuesta enviado por el usuario Armen no esta asociada al comentario
2012-05-31 21:30:23,273 ERROR EC-018:Error la respuesta enviado por el usuario Armen no esta asociada al comentario
2012-05-31 21:30:52,459 ERROR EC-018:Error la respuesta enviado por el usuario Carlos18 no esta asociada al comentario
2012-05-31 21:30:52,459 ERROR EC-018:Error la respuesta enviado por el usuario Carlos18 no esta asociada al comentario
2012-05-31 21:30:52,459 ERROR EC-018:Error la respuesta enviado por el usuario Carlos18 no esta asociada al comentario
2012-05-31 21:30:52,459 ERROR EC-018:Error la respuesta enviado por el usuario Carlos18 no esta asociada al comentario
2012-05-31 21:31:00,016 ERROR EC-017:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:31:00,016 ERROR EC-017:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:31:00,016 ERROR EC-017:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:31:00,016 ERROR EC-017:Error el usuario Carlos18 envio un token incorrecto
2012-05-31 21:31:05,599 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:31:05,599 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:31:05,599 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:31:05,599 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-05-31 21:31:36,856 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:31:36,856 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:31:36,856 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:31:36,856 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:32:06,215 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:32:06,215 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:32:06,215 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:32:06,215 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:34:57,082 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:34:57,082 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:34:57,082 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:34:57,082 ERROR EC-016:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:35:57,460 ERROR EC-017:Error el usuario sCarlos18 envio un token incorrecto
2012-05-31 21:35:57,460 ERROR EC-017:Error el usuario sCarlos18 envio un token incorrecto
2012-05-31 21:35:57,460 ERROR EC-017:Error el usuario sCarlos18 envio un token incorrecto
2012-05-31 21:35:57,460 ERROR EC-017:Error el usuario sCarlos18 envio un token incorrecto
2012-05-31 21:36:27,969 ERROR EC-017:Error el usuario yo envio un token incorrecto
2012-05-31 21:36:27,969 ERROR EC-017:Error el usuario yo envio un token incorrecto
2012-05-31 21:36:27,969 ERROR EC-017:Error el usuario yo envio un token incorrecto
2012-05-31 21:36:27,969 ERROR EC-017:Error el usuario yo envio un token incorrecto
2012-05-31 21:36:43,683 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:36:43,683 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:36:43,683 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:36:43,683 ERROR EC-017:Error el usuario Yo envio un token incorrecto
2012-05-31 21:37:50,450 ERROR EC-025:Error el comentario 1 no existe
2012-05-31 21:37:50,450 ERROR EC-025:Error el comentario 1 no existe
2012-05-31 21:37:50,450 ERROR EC-025:Error el comentario 1 no existe
2012-05-31 21:37:50,450 ERROR EC-025:Error el comentario 1 no existe
2012-05-31 21:41:19,691 ERROR EC-023:Error el comentario: 1 no existe
2012-05-31 21:41:19,691 ERROR EC-023:Error el comentario: 1 no existe
2012-05-31 21:41:19,691 ERROR EC-023:Error el comentario: 1 no existe
2012-05-31 21:41:19,691 ERROR EC-023:Error el comentario: 1 no existe
2012-05-31 21:41:25,950 ERROR EC-021:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:41:25,950 ERROR EC-021:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:41:25,950 ERROR EC-021:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:41:25,950 ERROR EC-021:Error el tiempo del token del usurario Carlos18 ha expirado
2012-05-31 21:44:01,692 ERROR EC-019:Error no se puede colocar Me Gusta al comentario: 21 otra vez
2012-05-31 21:44:01,692 ERROR EC-019:Error no se puede colocar Me Gusta al comentario: 21 otra vez
2012-05-31 21:44:01,692 ERROR EC-019:Error no se puede colocar Me Gusta al comentario: 21 otra vez
2012-05-31 21:44:01,692 ERROR EC-019:Error no se puede colocar Me Gusta al comentario: 21 otra vez
2012-06-01 07:24:40,560 ERROR Internal Server Error: /Usuario/iniciar_sesion/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 209, in iniciarSesion
    logging.error('EU-007:Error al tratar de inciar sesion con el nickname '+nickName+ ' y el password '+password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 07:25:41,441 ERROR Internal Server Error: /Usuario/iniciar_sesion/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 209, in iniciarSesion
    logging.error('EU-007:Error al tratar de inciar sesion con el nickname '+nickName+ ' y el password '+password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 07:26:04,990 ERROR Internal Server Error: /Usuario/iniciar_sesion/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 209, in iniciarSesion
    logging.error('EU-007:Error al tratar de inciar sesion con el nickname '+nickName+ ' y el password '+password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 07:27:29,301 ERROR Internal Server Error: /Usuario/iniciar_sesion/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 209, in iniciarSesion
    logging.error('EU-007:Error al tratar de inciar sesion con el nickname '+nickName+ ' y el password '+password)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 07:55:08,549 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:55:26,613 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:55:27,958 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:55:28,792 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:55:29,376 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:55:38,502 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:56:19,348 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:56:24,164 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 07:56:26,759 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 08:01:53,203 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 08:03:57,186 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos80 y el password 1234
2012-06-01 08:08:56,020 ERROR EU-007:Error al tratar de inciar sesion con el nickname armen y el password armen
2012-06-01 08:12:07,765 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:12:11,965 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:12:54,814 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:12:57,886 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:16:46,262 ERROR EU-007:Error al tratar de inciar sesion con el nickname armen y el password ad
2012-06-01 08:18:09,417 ERROR EU-007:Error al tratar de inciar sesion con el nickname 1 y el password 1
2012-06-01 08:18:37,703 ERROR EU-007:Error al tratar de inciar sesion con el nickname armen y el password 1234
2012-06-01 08:19:19,263 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:19:29,061 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:19:31,078 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 08:21:20,377 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 09:39:17,709 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 09:39:17,764 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 09:42:21,792 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 09:42:21,793 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 09:50:44,980 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 09:50:54,156 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 09:51:06,625 ERROR EU-008:Error el usuario Carlos2 tiene un token vigente
2012-06-01 09:51:29,752 ERROR EU-008:Error el usuario Armen tiene un token vigente
2012-06-01 09:53:41,033 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 09:53:41,034 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 09:58:32,377 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 09:59:30,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:02:55,714 ERROR EU-001:El usuario Armen666 ya se encuentra registrado
2012-06-01 10:02:55,714 ERROR EU-001:El usuario Armen666 ya se encuentra registrado
2012-06-01 10:09:04,297 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:04,297 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:04,297 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:50,194 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:50,194 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:50,194 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:09:50,194 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:12:19,703 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:12:19,703 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:12:19,703 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:12:19,703 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:12:19,703 ERROR EU-001:El usuario Armen999 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:15:21,487 ERROR EU-001:El usuario Armen000 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:16:20,755 ERROR EU-001:El usuario Armen9990 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:17:40,884 ERROR EU-001:El usuario Armen9991 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:18:38,833 ERROR EU-001:El usuario Armen99912 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:20:19,604 ERROR EU-001:El usuario Armen99913 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:22:43,622 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:24:38,129 ERROR EU-001:El usuario Armen999145 ya se encuentra registrado
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,553 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:38:25,554 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:40:57,658 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:46,300 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:41:53,540 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:42:35,687 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:50:17,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,043 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:56:03,044 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,379 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 10:59:34,380 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,902 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:01:52,904 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,357 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:04:21,358 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,728 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:05:11,729 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,511 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:07:27,512 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,726 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:13,727 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:08:27,013 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:09:22,670 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,774 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:10:44,775 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:20,974 ERROR EU-001:El usuario armen ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:12:45,170 ERROR EU-001:El usuario Armen0000 ya se encuentra registrado
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,819 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:13:26,820 ERROR Internal Server Error: /Usuario/registrar_usuario/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/usuario/ProyectoDesarrolloSoftware/misitio/misitio/views/viewsUsuario.py", line 90, in registrarUsuario
    return render_to_response('errorMensaje.xml', {'errorMensaje': "Error al tratar de registrar al usuario "+elUsuario.nickName},mimetype='application/xml')
TypeError: cannot concatenate 'str' and 'NoneType' objects
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:42:28,945 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:43:51,123 ERROR EU-001:El usuario Carlos2 ya se encuentra registrado
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 11:51:34,061 ERROR EU-007:Error al tratar de inciar sesion con el nickname Armen y el password 1234
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:17:52,016 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password fdfh
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:23:48,887 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password asa
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:25:15,427 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:26:43,836 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos y el password ssasas
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:27:00,077 ERROR EU-007:Error al tratar de inciar sesion con el nickname as y el password ass
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:50,747 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:52,493 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:54:59,807 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 14:57:17,138 ERROR EU-007:Error al tratar de inciar sesion con el nickname fgedhf y el password fjfj
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:03:56,514 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:07,094 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:17,251 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:04:20,787 ERROR EU-007:Error al tratar de inciar sesion con el nickname Carlos18 y el password 123423
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:05:29,149 ERROR EU-008:Error el usuario Carlos18 tiene un token vigente
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:06:41,462 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:07:11,509 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:08,848 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:08:26,116 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:10:11,168 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:11:54,463 ERROR EU-001:El usuario Armen9 ya se encuentra registrado
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 15:12:13,167 ERROR EU-002:Conexion no valida para el medio de persistencia al tratar de registrar al usuario
2012-06-01 16:01:17,423 ERROR EC-013:Error el usuario Cisco tiene un token vigente
2012-06-01 16:02:13,438 ERROR EC-013:Error el usuario Cisco tiene un token vigente
2012-06-01 16:04:20,610 ERROR EC-013:Error el usuario Cisco tiene un token vigente
2012-06-01 16:04:42,797 ERROR EC-013:Error el usuario Cisco tiene un token vigente
2012-06-01 16:36:15,054 ERROR EC-016:Error el tiempo del token del usurario Cisco ha expirado
